### ISSUE TITLE
mustache: Causes fatal error

### ISSUE THREAD

**Issue by thosakwe** [angel-dart/roadmap#3]
# Description of problem
*Occurs in mustache*

On a `FileSystemException`, the status remains 200, and the error thrown is fatal. Not only is it fatal, but it isn't caught by `errors` (which shouldn't even be possible???).

## Angel version:
1.0.0-alpha

## How urgently do you need the issue to be fixed?
Not super urgent, as the solution is simply to ensure that your views exist.

## Steps to reproduce error:
1. Set up mustache view engine
2. Call `res.render` with the name of a view file that does not exist.

## Error message, stack trace and output (if available)
```
FileSystemException: View "fail" was not found., path = 'fail.mustache'
#0      mustache.<anonymous closure>.<<anonymous closure>_async_body>.<anonymous closure>.<<anonymous closure>_async_body> (package:angel_mustache/angel_mustache.dart:31:14)
#1      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#2      _rootRunUnary (dart:async/zone.dart:1158)
#3      _CustomZone.runUnary (dart:async/zone.dart:1037)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#5      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#6      _Future._propagateToListeners (dart:async/future_impl.dart:667)
#7      _Future._completeWithValue (dart:async/future_impl.dart:477)
#8      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#9      _rootRun (dart:async/zone.dart:1150)
#10     _CustomZone.run (dart:async/zone.dart:1026)
#11     _CustomZone.runGuarded (dart:async/zone.dart:924)
#12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
Unhandled error occurred: Bad state: Header already sent
#0      _HttpResponse.statusCode= (dart:io/http_impl.dart:524)
#1      configureAfter.<configureAfter_async_body>.<anonymous closure>.<<anonymous closure>_async_body> (package:angel/src/routes/routes.dart:69:9)
#2      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#3      _rootRun (dart:async/zone.dart:1146)
#4      _CustomZone.run (dart:async/zone.dart:1026)
```

**Comment by thosakwe** [comment]
Actually, it is catchable by `errors`. Plus, this should occur, seeing as nonexistent views shouldn't be rendered.
